#!/bin/bash
# migrate-helm-config.sh - Convert cluster_helm HCL to YAML format
#
# Usage:
#   ./migrate-helm-config.sh terraform.tfvars > helm-values.yaml
#   ./migrate-helm-config.sh < terraform.tfvars > helm-values.yaml
#
# This script helps migrate from the deprecated cluster_helm HCL variable
# to the new cluster_helm_yaml YAML format in terraform-zcompute-k8s v1.1.
#
# Requirements: terraform, jq

set -euo pipefail

usage() {
    cat <<EOF
Usage: $(basename "$0") [TFVARS_FILE]

Convert cluster_helm HCL configuration to YAML format.

Arguments:
  TFVARS_FILE    Path to terraform.tfvars containing cluster_helm (optional)
                 If not provided, reads from stdin

Output:
  YAML configuration suitable for cluster_helm_yaml variable

Example:
  # From file
  $(basename "$0") terraform.tfvars > helm-values.yaml

  # From stdin
  echo 'cluster_helm = { flannel = { config = { podCidr = "10.0.0.0/8" } } }' | $(basename "$0")

Migration steps:
  1. Run this script to convert your existing cluster_helm to YAML
  2. Save output to a .yaml file or use inline in cluster_helm_yaml
  3. Remove cluster_helm from your terraform.tfvars
  4. Add cluster_helm_yaml or cluster_helm_values_dir to your config

For more information, see the module documentation.
EOF
    exit 0
}

# Check dependencies
command -v terraform >/dev/null 2>&1 || { echo "Error: terraform required" >&2; exit 1; }
command -v jq >/dev/null 2>&1 || { echo "Error: jq required" >&2; exit 1; }

# Handle help flag
[[ "${1:-}" == "-h" || "${1:-}" == "--help" ]] && usage

# Create temp directory for terraform workspace
TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

# Create minimal terraform config to parse cluster_helm
cat > "$TMPDIR/main.tf" <<'HCLEOF'
variable "cluster_helm" {
  type    = any
  default = {}
}

output "cluster_helm_yaml" {
  value = var.cluster_helm
}
HCLEOF

# Get input (file or stdin)
if [[ -n "${1:-}" ]]; then
    if [[ ! -f "$1" ]]; then
        echo "Error: File not found: $1" >&2
        exit 1
    fi
    # Copy the whole tfvars file - terraform will parse only what it needs
    cp "$1" "$TMPDIR/terraform.tfvars"
else
    cat > "$TMPDIR/terraform.tfvars"
fi

# Initialize and get output as JSON
cd "$TMPDIR"
terraform init -backend=false >/dev/null 2>&1

# Get cluster_helm as JSON via terraform console
# Note: terraform console wraps output in quotes, so we strip outer quotes and unescape inner ones
JSON=$(terraform console -var-file=terraform.tfvars <<< "jsonencode(var.cluster_helm)" 2>/dev/null | sed 's/^"//;s/"$//' | sed 's/\\"/"/g')

# Check if we got valid JSON
if ! echo "$JSON" | jq . >/dev/null 2>&1; then
    echo "# Error: Could not parse cluster_helm configuration" >&2
    echo "# Make sure the input file contains a valid cluster_helm block" >&2
    exit 1
fi

# Check if empty
if [[ "$JSON" == "{}" ]]; then
    echo "# No cluster_helm configuration found in input"
    echo "# Nothing to migrate"
    exit 0
fi

# Convert JSON to YAML-like format
# This produces a format suitable for cluster_helm_yaml
echo "# Migrated from cluster_helm HCL configuration"
echo "# Generated by migrate-helm-config.sh"
echo "#"
echo "# Use this content with cluster_helm_yaml variable:"
echo "#   cluster_helm_yaml = <<-YAML"
echo "#     <paste content below>"
echo "#   YAML"
echo "#"
echo "# Or save to a file and use cluster_helm_values_dir"
echo ""

# Convert JSON to YAML using jq
# Each top-level key is a chart name
echo "$JSON" | jq -r '
  to_entries[] |
  "---",
  "\(.key):",
  (
    .value | to_entries[] |
    if .value | type == "object" then
      "  \(.key):",
      (
        .value | to_entries[] |
        if .value | type == "object" then
          "    \(.key):",
          (
            .value | to_entries[] |
            "      \(.key): \(.value | @json)"
          )
        else
          "    \(.key): \(.value | @json)"
        end
      )
    elif .value | type == "array" then
      "  \(.key): \(.value | @json)"
    else
      "  \(.key): \(.value | @json)"
    end
  )
' 2>/dev/null || {
    # Fallback: output JSON with note
    echo "# Could not convert to YAML automatically."
    echo "# JSON format below (Terraform accepts JSON in YAML variables):"
    echo ""
    echo "$JSON" | jq .
}
